apiVersion: apps/v1
kind: Deployment
metadata:
  name: rekonfig
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rekonfig
  template:
    metadata:
      labels:
        name: rekonfig
    spec:
      serviceAccountName: rekonfig
      containers:
        - name: rekonfig
          image: andy2046/rekonfig:latest
          command:
          - rekonfig
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          env:
          - name: WATCH_NAMESPACE
            value: ""
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "rekonfig"
